name: Capture screenshots

on:
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          version: 12
      - name: Capture screenshots and commit
        env:
          GITHUB_API_TOKEN: ${{secrets.GITHUB_API_TOKEN}}
        run: |
          yarn
          yarn build
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/mdx-js/showcase.git
          git config --global user.email "johnotander+bot@gmail.com"
          git config --global user.name "Johno Bot"
          git add .
          git commit -m "Captured latest screenshots"
          git push
